/* =====================================================================
   Skeletal System & Bone Histology Quiz — question bank
   Weeks 7-9 lecture content (150 MCQs) + slide identification round.
   answer index `a` is 0-based: A=0, B=1, C=2, D=3, E=4
   ===================================================================== */

const SECTIONS = {
  1: "Part 1 · Bone anatomy, growth & calcium homeostasis (Q1–50)",
  2: "Part 2 · Cell lineages, ossification, fracture repair (Q51–100)",
  3: "Part 3 · Bone matrix, histology, fractures & joints (Q101–150)"
};

const QUESTIONS = [
// ---------------- PART 1 (1-50) ----------------
{s:1,q:"According to the Week 8 lecture slides, which of the following is a primary function of the skeletal system?",o:["Generation of electrical action potentials","Synthesis of Vitamin C","Blood cell production (hematopoiesis)","Regulation of body temperature","Filtration of cellular waste products"],a:2},
{s:1,q:"The skeletal system is responsible for the storage and release of energy in the form of what substance?",o:["Glycogen","Fat","ATP","Lactic Acid","Glucose"],a:1},
{s:1,q:"Which two specific minerals are highlighted in the lecture slides as being actively stored and released by the skeletal system?",o:["Sodium and Potassium","Iron and Zinc","Calcium and Phosphate (PO4 3-)","Magnesium and Chloride","Copper and Sulfur"],a:2},
{s:1,q:"When examining the gross anatomy of a long bone, what is the anatomical term for the long, tubular central shaft?",o:["Epiphysis","Metaphysis","Diaphysis","Endosteum","Articular cartilage"],a:2},
{s:1,q:"What is the name of the wide regions located at the extreme proximal and distal ends of a long bone?",o:["Diaphysis","Epiphysis","Metaphysis","Periosteum","Medullary cavity"],a:1},
{s:1,q:"The narrow transition zone where the diaphysis meets the epiphysis in a long bone is called the:",o:["Metaphysis","Endosteum","Medullary cavity","Central canal","Articular cartilage"],a:0},
{s:1,q:"What specific structure, essential for longitudinal bone growth, is located within the metaphysis of a growing bone?",o:["Nutrient artery","Yellow bone marrow","Epiphyseal plate (growth plate)","Spongy bone network","Periosteum"],a:2},
{s:1,q:"The hollow, central space running down the middle of the diaphysis is known as the:",o:["Central canal","Lacuna","Medullary cavity","Epiphyseal line","Trabecular network"],a:2},
{s:1,q:"In an adult long bone, what substance primarily fills the medullary cavity?",o:["Red bone marrow","Yellow bone marrow","Synovial fluid","Cerebrospinal fluid","Pure collagen fibers"],a:1},
{s:1,q:"What is the thin, delicate membranous lining found inside the medullary cavity of a long bone?",o:["Periosteum","Epidermis","Endosteum","Epimysium","Perichondrium"],a:2},
{s:1,q:"The tough, vascularized outer membrane covering the external surface of the bone (except at the joints) is called the:",o:["Endosteum","Periosteum","Articular cartilage","Lamina propria","Mesothelium"],a:1},
{s:1,q:"What structure directly covers the proximal and distal epiphyses to provide a smooth surface for joint articulation?",o:["Periosteum","Yellow bone marrow","Articular cartilage","Endosteum","Epiphyseal line"],a:2},
{s:1,q:"In the proximal epiphysis of a long bone, the internal web-like matrix is primarily composed of:",o:["Compact bone","Spongy bone","Dense regular connective tissue","Hyaline cartilage","Yellow bone marrow"],a:1},
{s:1,q:"Which nutrient is explicitly required to synthesize calcium phosphate and calcium carbonate in bone tissue?",o:["Vitamin K","Magnesium","Calcium","Fluoride","Omega-3 fatty acids"],a:2},
{s:1,q:"Calcium phosphate and calcium carbonate combine to form which specific crystals that give bone its extreme hardness?",o:["Keratohyalin crystals","Calcium oxalate crystals","Hydroxyapatite crystals","Uric acid crystals","Cholesterol crystals"],a:2},
{s:1,q:"According to the nutrient chart, what is the primary role of Vitamin D in bone health?",o:["It acts as a structural component of the bone matrix.","It directly builds collagen fibers.","It is required for the absorption of calcium in the body.","It prevents the differentiation of osteoclasts.","It lowers blood pH levels."],a:2},
{s:1,q:"Which nutrient is noted for supporting bone mineralization and having a potential synergistic effect with Vitamin D?",o:["Vitamin K","Vitamin C","Fluoride","Omega-3 fatty acids","Magnesium"],a:0},
{s:1,q:"Along with Calcium, both Magnesium and ________ are listed as essential structural components of bone tissue.",o:["Potassium","Iron","Zinc","Fluoride","Sodium"],a:3},
{s:1,q:"Omega-3 fatty acids are beneficial for bone health because they reduce inflammation that may otherwise interfere with the function of which specific bone cells?",o:["Chondrocytes","Osteoclasts","Osteoblasts","Macrophages","Erythrocytes"],a:2},
{s:1,q:"What is the specific term for the type of bone growth that increases the thickness (diameter) of a bone?",o:["Interstitial growth","Endochondral ossification","Appositional growth","Longitudinal growth","Hypertrophic growth"],a:2},
{s:1,q:"During appositional growth, bone thickness increases while the bone simultaneously maintains a hollow center. This relies heavily on the activity of which cells at the superficial surface?",o:["Superficial osteoclasts","Superficial osteoblasts","Deep chondrocytes","Superficial fibroblasts","Deep macrophages"],a:1},
{s:1,q:"Which type of bone growth is responsible for increasing the longitudinal length of long bones?",o:["Appositional growth","Interstitial (longitudinal) growth","Transverse growth","Periosteal growth","Calcification growth"],a:1},
{s:1,q:"Endochondral ossification is provided as a classic example of which type of growth?",o:["Appositional growth","Interstitial (longitudinal) growth","Flat bone development","Metacarpal expansion","Extensibility"],a:1},
{s:1,q:"The epiphyseal growth plate is divided into several distinct cellular zones. Which zone is located at the very top, closest to the epiphysis?",o:["Zone of proliferation","Zone of ossification","Reserve cartilage","Zone of calcification","Zone of maturation and hypertrophy"],a:2},
{s:1,q:"In the epiphyseal plate, which zone is primarily characterized by active \"growth\" and cellular division?",o:["Reserve cartilage","Zone of proliferation","Zone of calcification","Zone of ossification","Zone of maturation and hypertrophy"],a:1},
{s:1,q:"Following the zone of proliferation in the epiphyseal plate, cells move into a zone where they enlarge. What is this zone called?",o:["Reserve cartilage","Zone of calcification","Zone of ossification","Zone of maturation and hypertrophy","Zone of interstitial spread"],a:3},
{s:1,q:"In the epiphyseal plate, what notable cellular event occurs in the Zone of Calcification?",o:["Massive cell division (mitosis)","Cells differentiate into neurons","Cell death","The cells shed their nuclei to become red blood cells","The cells begin producing melanin"],a:2},
{s:1,q:"What is the final, deepest zone of the epiphyseal plate (closest to the diaphysis) where the actual new bone tissue is formed?",o:["Reserve cartilage","Zone of proliferation","Zone of calcification","Zone of ossification","Zone of maturation and hypertrophy"],a:3},
{s:1,q:"Based on the Week 8 Calcium Homeostasis diagram, the Parathyroid gland releases hormones that primarily act to regulate the levels of serum Ca2+ by targeting the bones, the intestines, and the:",o:["Liver","Kidneys","Lungs","Spleen","Pancreas"],a:1},
{s:1,q:"Calcium homeostasis is described in the case study as being \"VERY complex\" because it involves multiple organs, multiple hormones, and synergy with which specific vitamin?",o:["Vitamin A","Vitamin C","Vitamin D","Vitamin K","Vitamin E"],a:2},
{s:1,q:"Bone cells originate from a specific embryonic tissue line. What is the specific lineage for osteogenic cells?",o:["Ectodermal lineage","Endodermal lineage","Mesenchymal lineage","Epithelial lineage","Neural crest lineage"],a:2},
{s:1,q:"According to the bone cell differentiation pathway, an osteoblast will eventually receive signals to differentiate into a mature:",o:["Osteoclast","Osteocyte","Chondrocyte","Fibroblast","Macrophage"],a:1},
{s:1,q:"The lecture notes explicitly state that heavy metals can dangerously accumulate in the body over time. In which organ system do these heavy metals primarily accumulate?",o:["Nervous system (Brain)","Cardiovascular system (Heart)","Skeletal system (Bones)","Integumentary system (Skin)","Digestive system (Liver)"],a:2},
{s:1,q:"In the lecture covering bone landmarks, the metacarpophalangeal joints are provided as an example. What is the common name for these specific joints?",o:["The elbows","The knees","The ankles","The knuckles","The shoulders"],a:3},
{s:1,q:"The radiocarpal joint is provided as an example of a bone landmark in the slides. What part of the body does this correspond to?",o:["The hip","The shoulder","The wrist","The jaw","The neck"],a:2},
{s:1,q:"A Week 9 PollEv participation question asks: \"How are you preparing for Quiz 4 (this WEDS) on bone tissue & the skeletal system?\" Based on the slide announcements, what specific topics does Quiz 4 cover?",o:["Nervous system and action potentials","Integumentary system only","Bone tissue, bone cells, and skeletal system structure & function","Chemistry of life and water properties","Muscle tissue and contraction cycles"],a:2},
{s:1,q:"Which blood vessel is visibly shown penetrating the diaphysis to supply the inner bone tissue with blood?",o:["Pulmonary artery","Carotid artery","Nutrient artery","Femoral artery","Aortic arch"],a:2},
{s:1,q:"The region of a long bone that eventually ossifies completely in adults to form the \"epiphyseal line\" is the:",o:["Diaphysis","Metaphysis","Medullary cavity","Periosteum","Articular cartilage"],a:1},
{s:1,q:"To ask about the epiphyseal plate in a different way: if a child breaks a long bone right at the metaphysis, which specific process of bone growth is most likely to be physically impaired?",o:["Appositional growth","Circumferential growth","Interstitial (longitudinal) growth","Transverse growth","Extensibility"],a:2},
{s:1,q:"If a patient is severely deficient in Vitamin K, what specific aspect of bone health will be compromised according to the nutrient chart?",o:["The ability to synthesize bone marrow","Bone mineralization","The physical structure of articular cartilage","The production of yellow bone marrow","The storage of fat in the diaphysis"],a:1},
{s:1,q:"Which of the following best describes the progression of cells through the epiphyseal plate, from the top (epiphysis end) down to the diaphysis?",o:["Reserve → Proliferation → Maturation → Calcification → Ossification","Ossification → Calcification → Maturation → Proliferation → Reserve","Proliferation → Reserve → Ossification → Maturation → Calcification","Maturation → Calcification → Ossification → Reserve → Proliferation","Reserve → Maturation → Proliferation → Ossification → Calcification"],a:0},
{s:1,q:"Which of the following statements best describes \"Appositional growth\"?",o:["It increases the length of the bone by adding cartilage to the epiphyseal plate.","It converts yellow bone marrow into red bone marrow.","It increases the thickness of the bone while keeping the inside hollow.","It creates new articular cartilage at the joint surfaces.","It relies entirely on osteoclasts destroying the outer bone layer."],a:2},
{s:1,q:"To ask about bone nutrients in a different way: which two components listed below both act directly as \"structural components of bone\"?",o:["Vitamin D and Vitamin K","Magnesium and Fluoride","Omega-3 fatty acids and Vitamin C","Iron and Zinc","Calcium and Sodium"],a:1},
{s:1,q:"Which of the following is NOT one of the explicit critical functions of the skeletal system listed in the Week 8 slides?",o:["Protection","Movement","Digestion of proteins","Support","Blood cell production"],a:2},
{s:1,q:"Which area of the long bone is covered by the periosteum?",o:["The interior walls of the medullary cavity","The exact surfaces where joints articulate","The external surface of the bone, except at the articular cartilage","The deep trabeculae of the spongy bone","The center of the osteon"],a:2},
{s:1,q:"Which part of the long bone acts as a reservoir specifically for fat storage?",o:["The epiphyseal plate","The red bone marrow","The yellow bone marrow","The endosteum","The articular cartilage"],a:2},
{s:1,q:"A PollEv question from Week 8 asks, \"What questions do you have about bone tissue?\" If a student asks how osteocytes are formed, what is the correct physiological answer based on the Week 9 review?",o:["They divide directly from other osteocytes via mitosis.","They differentiate from white blood cells.","They differentiate from osteoblasts after receiving specific signals.","They are formed by the fusion of multiple osteoclasts.","They are produced by the yellow bone marrow."],a:2},
{s:1,q:"In the context of bone diseases covered in Week 9, the slides specifically highlight that certain cancers target bone. Which cells would a bone-specific cancer most likely affect?",o:["Simple squamous epithelial cells","Adipocytes in the hypodermis","Cells of the mesenchymal/osteogenic lineage","Neurons in the central nervous system","Keratinocytes"],a:2},
{s:1,q:"According to the Calcium Homeostasis flow chart, the Parathyroid gland releases its hormone when:",o:["Serum Ca2+ levels fall and need to be increased.","Blood sugar levels are too high.","The body is severely dehydrated.","The epiphyseal plate closes completely.","White blood cell counts drop."],a:0},
{s:1,q:"Red bone marrow is essential for hematopoiesis. In the diagram of the long bone, where is the red bone marrow primarily located?",o:["Within the central canal of the osteon","Throughout the entire medullary cavity of the diaphysis","Within the spongy bone of the proximal epiphysis","Inside the periosteum","Within the articular cartilage"],a:2},

// ---------------- PART 2 (51-100) ----------------
{s:2,q:"According to the OpenStax chapter review, which function of the skeletal system would be especially important if you were in a car accident?",o:["Storage of minerals","Protection of internal organs","Facilitation of movement","Fat storage","Generation of body heat"],a:1},
{s:2,q:"Based on the OpenStax review questions, without red marrow, bones would NOT be able to ________.",o:["Store phosphate","Store calcium","Make blood cells (hematopoiesis)","Move like levers","Store triglycerides (fat)"],a:2},
{s:2,q:"Most of the bones of the arms and hands are long bones; however, the bones in the wrist (carpals) are categorized as ________.",o:["Flat bones","Short bones","Sesamoid bones","Irregular bones","Sutural bones"],a:1},
{s:2,q:"Sesamoid bones are a special type of short bone that form embedded in ________.",o:["Joints","Muscles","Ligaments","Tendons","Articular cartilage"],a:3},
{s:2,q:"According to your lecture notes on cell lineages, what is the ultimate embryonic stem cell origin of both the cartilage cells (chondrocytes) and bone cells (osteocytes) during skeletal development?",o:["Ectodermal stem cells","Mesenchymal stem cells","Endodermal stem cells","Hematopoietic stem cells","Epithelial stem cells"],a:1},
{s:2,q:"In the bone development lineage, mesenchymal stem cells differentiate into osteoprogenitor cells, which then mature into ________, the cells responsible for actively secreting new bone matrix.",o:["Osteoclasts","Osteoblasts","Chondroblasts","Osteocytes","Fibroblasts"],a:1},
{s:2,q:"If a mesenchymal stem cell follows the cartilage lineage during fetal development, it will first differentiate into a ________ before maturing into a chondrocyte.",o:["Chondroblast","Osteoclast","Fibroblast","Macrophage","Osteocyte"],a:0},
{s:2,q:"There are two different pathways for bone development. The process that forms the flat bones of the skull and the clavicles by developing directly from mesenchymal fibrous membranes is called:",o:["Endochondral ossification","Interstitial growth","Appositional ossification","Intramembranous ossification","Secondary ossification"],a:3},
{s:2,q:"Endochondral ossification differs from intramembranous ossification because it specifically requires which of the following before actual bone can form?",o:["A fibrous membrane","A hyaline cartilage template/model","A fully formed medullary cavity","An external fibrous callus","A dense regular connective tissue model"],a:1},
{s:2,q:"What is the very first cellular step in the process of intramembranous ossification?",o:["Osteoclasts hollow out a medullary cavity.","Mesenchymal cells cluster together and condense to form an ossification center.","Chondrocytes swell and die.","A bone collar forms around the diaphysis.","Red blood cells convert into osteoblasts."],a:1},
{s:2,q:"During early bone formation, the newly formed, immature bone tissue is characterized by a random, unorganized collagen matrix. This immature bone is called ________ bone, and it is later remodeled into mature ________ bone.",o:["Woven; Lamellar","Compact; Spongy","Trabecular; Cancellous","Lamellar; Woven","Diaphyseal; Epiphyseal"],a:0},
{s:2,q:"In the first step of endochondral ossification, the mesenchyme develops into a hyaline cartilage model. What happens to the chondrocytes within the center of this model shortly after?",o:["They multiply rapidly to form an osteon.","They swell (hypertrophy) and calcify the surrounding matrix before dying.","They transform directly into osteoblasts.","They migrate out of the bone into the bloodstream.","They secrete yellow bone marrow."],a:1},
{s:2,q:"During step 2 of endochondral ossification, blood vessels penetrate the perichondrium at the center of the diaphysis. This triggers the perichondrium to officially convert into what structure?",o:["The epiphyseal plate","The medullary cavity","The periosteum","The articular cartilage","The endosteum"],a:2},
{s:2,q:"In step 3 of endochondral ossification, osteoclasts make an opening for blood vessels to enter the center of the diaphysis, transporting osteoblasts into the area. This newly vascularized region of bone formation is called the:",o:["Secondary ossification center","Primary ossification center","Nutrient foramen","Epiphyseal line","Hard callus"],a:1},
{s:2,q:"By step 4 of endochondral ossification, what large anatomical feature is carved out in the center of the diaphysis by osteoclast activity?",o:["A lacuna","The central canal","The medullary cavity","A trabecula","The primary ossification center"],a:2},
{s:2,q:"Where do the secondary ossification centers form during the later stages of endochondral ossification?",o:["In the direct center of the diaphysis","Within the periosteum","In the epiphyses (the ends of the bone)","Inside the medullary cavity","Along the articular cartilage"],a:2},
{s:2,q:"After endochondral ossification is mostly complete, hyaline cartilage remains in only two places on a growing long bone. Where are these two places?",o:["The diaphysis and the medullary cavity","The periosteum and the endosteum","The articular cartilage and the epiphyseal plate","The primary and secondary ossification centers","The central canals and perforating canals"],a:2},
{s:2,q:"From the OpenStax review: In endochondral ossification, what exactly happens to the chondrocytes in the center of the cartilaginous model?",o:["They develop into osteocytes.","They die in the calcified matrix that surrounds them and form the medullary cavity.","They grow and form the periosteum.","They group together to form the primary ossification center.","They migrate to the articular cartilage."],a:1},
{s:2,q:"When observing a slide of spongy bone, you see a network of bony spikes called trabeculae. Where are the osteoblasts and osteoclasts primarily located in relation to these trabeculae?",o:["Trapped inside the central lacunae","Floating freely in the center of the blood vessels","Lined up along the outer surface (the endosteum) wrapping the trabeculae","Clustered tightly inside the concentric lamellae","Embedded deeply within the yellow bone marrow"],a:2},
{s:2,q:"When looking at a cross-section of compact bone, you notice dark, spider-like spaces organized in concentric rings around a central canal. What are the specific mature bone cells that reside inside these small spaces (lacunae)?",o:["Osteoclasts","Chondrocytes","Osteogenic cells","Osteocytes","Osteoblasts"],a:3},
{s:2,q:"You are identifying a bone tissue slide and notice it lacks osteons and central canals entirely, but it does contain an open lattice of trabeculae surrounded by red bone marrow. What type of tissue are you looking at?",o:["Compact bone","Spongy (cancellous) bone","Hyaline cartilage","Dense regular connective tissue","Fibrocartilage"],a:1},
{s:2,q:"An \"open\" or \"compound\" bone fracture is considered a major medical emergency because it carries a significantly high risk of:",o:["Spontaneous bone fusion","Severe infection due to the broken bone piercing the skin","Immediate onset of osteoporosis","Overproduction of red blood cells","Excessive calcification of the fracture hematoma"],a:1},
{s:2,q:"A severe bone fracture where the bone is broken or crushed into three or more separate pieces is classified as a ________ fracture.",o:["Transverse","Oblique","Comminuted","Spiral","Impacted"],a:2},
{s:2,q:"Which type of fracture occurs when one fragment of a broken bone is forcefully driven and compressed into the other fragment?",o:["Greenstick","Impacted","Spiral","Transverse","Oblique"],a:1},
{s:2,q:"What is the immediate physiological response (Step 1) of the body when a bone fractures?",o:["Osteoclasts immediately dissolve the entire bone to restart the process.","A fracture hematoma (blood clot) forms to stop the bleeding.","A bony callus of spongy bone is created.","Hyaline cartilage completely covers the fracture.","The medullary cavity permanently seals shut."],a:1},
{s:2,q:"During the second stage of fracture repair, a \"soft callus\" forms to stabilize the break. What type of tissue primarily makes up this soft, internal/external callus?",o:["Spongy bone","Compact bone","Dense regular connective tissue","Fibrocartilage","Adipose tissue"],a:3},
{s:2,q:"In the third stage of fracture repair, the soft callus is replaced by a \"hard callus.\" Which bone cells are responsible for producing the new trabecular bone of this hard callus?",o:["Chondrocytes","Osteoclasts","Osteoblasts","Macrophages","Fibroblasts"],a:2},
{s:2,q:"The final stage of bone fracture repair is \"Remodeling.\" What primarily occurs during this phase?",o:["The initial fracture hematoma is formed.","The internal callus is built by chondrocytes.","The spongy/trabecular bone of the hard callus is replaced by stronger compact bone.","All bone cells in the area undergo apoptosis.","The periosteum is completely stripped away."],a:2},
{s:2,q:"From the OpenStax review: The very first type of bone tissue to form during fracture repair (the hard callus) is ________ bone.",o:["Compact","Lamellar","Spongy","Dense","Cortical"],a:2},
{s:2,q:"Calcium homeostasis involves a complex feedback loop. If your blood calcium levels drop too low (hypocalcemia), which specific gland acts as the control center to release a hormone that corrects this?",o:["The Thyroid gland","The Pituitary gland","The Parathyroid gland","The Adrenal gland","The Pancreas"],a:2},
{s:2,q:"When Parathyroid Hormone (PTH) is released in response to low blood calcium, what direct effect does it have on bone tissue?",o:["It triggers osteoclast apoptosis.","It inhibits osteoclast activity to save bone matrix.","It activates osteoclasts to break down bone and release calcium into the blood.","It forces osteoclasts to turn into osteoblasts.","It causes osteoclasts to absorb excess calcium from the blood."],a:2},
{s:2,q:"During calcium homeostasis, PTH also targets the kidneys. What is the kidney's response to PTH?",o:["It increases the excretion of calcium into the urine.","It increases the reabsorption of calcium from the urine back into the bloodstream.","It shuts down urine production completely.","It secretes excess calcium into the stomach.","It converts calcium into potassium."],a:1},
{s:2,q:"PTH stimulates the kidneys to activate a specific vitamin, which then travels to the intestines to dramatically increase the absorption of calcium from your diet. Which vitamin is this?",o:["Vitamin A","Vitamin C","Vitamin D (Calcitriol)","Vitamin K","Vitamin E"],a:2},
{s:2,q:"Hypercalcemia (abnormally high blood calcium) can occur if the parathyroid gland becomes overactive and ignores feedback loops. What effect would constant, overactive PTH secretion have on your bones?",o:["It would make them excessively thick and dense.","It would cause bone tissue to be broken down excessively by osteoclasts, leading to brittle, weak bones.","It would turn bone tissue back into hyaline cartilage.","It would stop longitudinal growth entirely.","It would increase the production of red bone marrow."],a:1},
{s:2,q:"Which hormone is released by the Thyroid gland in response to elevated (high) blood calcium levels, acting to inhibit osteoclast activity and lower blood calcium?",o:["Parathyroid Hormone","Calcitonin","Insulin","Glucagon","Melatonin"],a:1},
{s:2,q:"Wolff's Law states that \"bones adapt to the mechanical loads placed upon them.\" If you start lifting heavy weights, what cellular response will occur to adapt to this increased stress?",o:["Osteoclasts will dissolve the bone to make it lighter.","Osteoblasts will deposit new bone matrix to make the bone thicker and stronger.","Chondrocytes will replace the compact bone with cartilage.","Osteocytes will immediately undergo apoptosis.","The medullary cavity will fill with synovial fluid."],a:1},
{s:2,q:"From the OpenStax review: Why are osteocytes spread out in bone tissue?",o:["They develop from mesenchymal cells that wander.","They travel rapidly through the capillaries.","The formation of osteoid spreads out the osteoblasts that formed the ossification centers, after which they become trapped as osteocytes.","They repel each other magnetically.","They migrate to the periosteum during adulthood."],a:2},
{s:2,q:"In your Week 9 slides, bone landmarks are described more by their function as joints. The metacarpophalangeal joints are provided as an example. What is the common name for these joints?",o:["The elbows","The ankles","The knuckles","The shoulders","The knees"],a:2},
{s:2,q:"A condition characterized by progressive bone loss that leads to weakened and brittle bones, often occurring in adults over 50 because bone resorption outpaces bone deposition, is called:",o:["Osteomalacia","Rickets","Osteoporosis","Craniosynostosis","Osteogenesis imperfecta"],a:2},
{s:2,q:"Soft, weak, and deformed bones (such as severely bowed legs) in children, usually caused by a severe Vitamin D or calcium deficiency, is known as:",o:["Osteoporosis","Rickets","Paget's disease","Osteoarthritis","Kyphosis"],a:1},
{s:2,q:"From the OpenStax review: Which of the following bones is (are) formed by intramembranous ossification?",o:["The metatarsals","The femur","The ribs","The flat bones of the cranium","The vertebrae"],a:3},
{s:2,q:"The area of a bone where the nutrient artery passes into the diaphysis forms what kind of functional bone marking?",o:["A facet","A fissure","A nutrient foramen (hole)","A condyle","A tuberosity"],a:2},
{s:2,q:"From the OpenStax review: Bones grow in diameter (thickness) due to bone formation ________.",o:["In the medullary cavity","Beneath the periosteum (appositional growth)","In the epiphyseal plate","Within the articular cartilage","Inside the central canal"],a:1},
{s:2,q:"From the OpenStax review: Which of the following represents the correct sequence of zones in the epiphyseal plate (from the epiphyseal side down toward the diaphysis)?",o:["Proliferation, reserve, maturation, calcification","Maturation, proliferation, reserve, calcification","Reserve, proliferation, maturation (hypertrophy), calcification","Calcification, reserve, proliferation, maturation","Ossification, calcification, reserve, maturation"],a:2},
{s:2,q:"A PollEv question variant: Based on Wolff's Law of mechanical stress, which individual would experience the most significant decrease in bone density?",o:["A professional weightlifter","An astronaut spending 6 months in zero gravity","A marathon runner","A basketball player","A construction worker"],a:1},
{s:2,q:"If you are looking at a bone histology slide and see tightly packed osteons with central canals, but absolutely no trabeculae or open marrow spaces, you are looking at:",o:["Spongy bone","Compact bone","Cancellous bone","Hyaline cartilage","Fibrocartilage"],a:1},
{s:2,q:"A fracture in which the bone breaks cleanly straight across the long axis of the diaphysis is called a:",o:["Spiral fracture","Comminuted fracture","Transverse fracture","Impacted fracture","Greenstick fracture"],a:2},
{s:2,q:"From the OpenStax review: How can a fractured diaphysis release fat globules into the bloodstream?",o:["The bone pierces fat stores in the skin.","The yellow marrow in the medullary cavity of the diaphysis is exposed and damaged.","The injury triggers the body to release fat from healthy bones.","The red marrow converts to fat to heal the fracture.","The periosteum rapidly synthesizes fat."],a:1},
{s:2,q:"If an osteogenic stem cell receives a signal to become a bone-forming cell, it differentiates into an osteoblast. Once that osteoblast surrounds itself completely with calcified bone matrix, it matures into a(n):",o:["Osteoclast","Chondroblast","Osteocyte","Macrophage","Fibrocyte"],a:2},
{s:2,q:"The skeletal system interacts closely with the urinary system and digestive system to maintain calcium balance. If serum calcium levels are dangerously high and calcitonin is released, which organ's activity will be decreased to prevent further calcium absorption into the blood?",o:["The heart","The brain","The intestines","The lungs","The skin"],a:2},

// ---------------- PART 3 (101-150) ----------------
{s:3,q:"Bone matrix is composed of both organic and inorganic materials. Which organic component provides bone with its flexibility and tensile strength, preventing it from constantly shattering?",o:["Hydroxyapatite","Calcium carbonate","Collagen fibers","Calcium phosphate","Yellow bone marrow"],a:2},
{s:3,q:"Which inorganic component of the bone matrix provides the bone with its extreme hardness and ability to withstand compressive forces?",o:["Proteoglycans","Glycoproteins","Hydroxyapatite crystals","Collagen bundles","Reticular fibers"],a:2},
{s:3,q:"While long bones have a tubular diaphysis, flat bones (like the cranial bones) have a different structure. A flat bone consists of a layer of spongy bone sandwiched between two layers of compact bone. What is the specific anatomical term for this spongy bone layer in a flat bone?",o:["The trabecular medullary cavity","The diploë","The endosteum","The epiphysis","The secondary ossification center"],a:1},
{s:3,q:"In the histology of compact bone, the concentric rings of calcified matrix that form a single osteon are called concentric lamellae. What is the term for the incomplete lamellae that fill the gaps between intact osteons, representing the remnants of older, remodeled osteons?",o:["Circumferential lamellae","Interstitial lamellae","Trabecular lamellae","Epiphyseal lamellae","Diaphyseal lamellae"],a:1},
{s:3,q:"Which type of lamellae wrap around the entire outer and inner circumference of the diaphysis, acting like the structural bands of a barrel?",o:["Concentric lamellae","Interstitial lamellae","Circumferential lamellae","Perforating lamellae","Osteonic lamellae"],a:2},
{s:3,q:"Inside an osteon, osteocytes are trapped inside lacunae. How do these trapped cells physically connect with one another to share nutrients and communicate?",o:["Through large central blood vessels","Through tiny, hair-like channels in the matrix called canaliculi","By physically leaving their lacunae and swimming through the matrix","Through the medullary cavity","Through the lymphatic system"],a:1},
{s:3,q:"Blood vessels running down the central canal of an osteon must connect with vessels in the periosteum and medullary cavity. They do this by traveling horizontally through:",o:["Canaliculi","Interstitial lamellae","Perforating (Volkmann's) canals","Trabeculae","The epiphyseal plate"],a:2},
{s:3,q:"Which specific bone cell is unique because it is massive, multi-nucleated, and originates from a white blood cell (macrophage) lineage rather than the mesenchymal stem cell lineage?",o:["Osteoblast","Osteocyte","Osteoclast","Osteoprogenitor cell","Chondroblast"],a:2},
{s:3,q:"Osteoclasts feature a \"ruffled border\" where they meet the bone surface. What is the physiological purpose of this ruffled border?",o:["To increase the surface area for secreting bone-dissolving acids and enzymes","To trap red blood cells","To absorb calcium directly from the bloodstream","To synthesize new collagen fibers","To divide and undergo mitosis rapidly"],a:0},
{s:3,q:"Where in a mature long bone would you specifically expect to find a population of osteogenic (stem) cells ready to differentiate into osteoblasts for repair or remodeling?",o:["Only within the yellow bone marrow","Embedded deep within the center of an osteon","In the periosteum and the cellular layer of the endosteum","Floating in the synovial fluid","Within the articular cartilage"],a:2},
{s:3,q:"From the OpenStax review: Which of the following bones is classified as an irregular bone?",o:["Femur","Carpal","Vertebra","Frontal bone","Patella"],a:2},
{s:3,q:"From the OpenStax review: The diaphysis of a long bone contains ________.",o:["Mostly spongy bone","The epiphyseal plate","Fat stores (yellow marrow)","Articular cartilage","Only red bone marrow"],a:2},
{s:3,q:"From the OpenStax review: Which of the following cells are the only bone cells capable of cell division (mitosis)?",o:["Osteoblasts","Osteocytes","Osteoclasts","Osteogenic cells","Chondrocytes"],a:3},
{s:3,q:"Intramembranous ossification begins when mesenchymal cells differentiate into osteoblasts and begin secreting an uncalcified, organic bone matrix. What is this initial uncalcified matrix called?",o:["Lamellae","Osteoid","Hydroxyapatite","Cartilage","Perichondrium"],a:1},
{s:3,q:"During intramembranous ossification, the initially formed spongy bone is eventually remodeled on its outer surfaces to form:",o:["A permanent hyaline cartilage model","The medullary cavity","A layer of compact bone","The secondary ossification center","Yellow bone marrow"],a:2},
{s:3,q:"In endochondral ossification, a hyaline cartilage model is used. What crucial event happens to the cartilage matrix in the primary ossification center right before the blood vessels invade?",o:["The cartilage cells rapidly divide to form the periosteum.","The cartilage matrix calcifies, cutting off nutrients and causing the central chondrocytes to die.","The cartilage permanently converts into yellow bone marrow.","The cartilage stretches to form articular cartilage.","The cartilage cells transform directly into red blood cells."],a:1},
{s:3,q:"During fetal development, the primary ossification center of a long bone forms in the diaphysis. Where do the secondary ossification centers form shortly before or after birth?",o:["In the medullary cavity","In the periosteum","In the epiphyses","In the central canals","In the flat bones of the skull"],a:2},
{s:3,q:"When bone is initially formed or repaired, the collagen fibers are laid down randomly in a crisscross pattern. This immature tissue is later remodeled into mature bone where the collagen is neatly aligned. What are these two tissues called?",o:["Compact bone remodeled into spongy bone","Woven bone remodeled into lamellar bone","Lamellar bone remodeled into woven bone","Trabecular bone remodeled into cancellous bone","Cartilage remodeled into woven bone"],a:1},
{s:3,q:"A fracture where the bone breaks, but the broken ends do NOT pierce the skin, is medically classified as a:",o:["Complete fracture","Open (Compound) fracture","Closed (Simple) fracture","Greenstick fracture","Comminuted fracture"],a:2},
{s:3,q:"A fracture in which the bone is NOT completely broken all the way through is called an incomplete fracture. What is the classic example of an incomplete fracture, common in children, where one side of the bone breaks while the other side only bends?",o:["Transverse fracture","Oblique fracture","Impacted fracture","Greenstick fracture","Spiral fracture"],a:3},
{s:3,q:"A fracture that occurs at an angle (not a straight 90 degrees) across the long axis of the bone is classified as a(n) ________ fracture.",o:["Transverse","Oblique","Spiral","Comminuted","Impacted"],a:1},
{s:3,q:"Which specific type of bone fracture is commonly caused by a severe twisting motion applied to the bone?",o:["Transverse fracture","Impacted fracture","Spiral fracture","Greenstick fracture","Comminuted fracture"],a:2},
{s:3,q:"The skin plays a crucial supporting role in calcium homeostasis. Without UV radiation hitting the skin to synthesize a Vitamin D precursor, the body cannot eventually produce calcitriol. Without calcitriol, what specifically fails to happen in the digestive system?",o:["The stomach fails to digest dietary proteins.","The intestines cannot absorb dietary calcium into the bloodstream.","The liver cannot produce bile.","The intestines rapidly excrete all calcium into feces.","The pancreas cannot release insulin."],a:1},
{s:3,q:"From the OpenStax review: Joints can be classified functionally based on their degree of movement. A joint that is completely immovable (like the sutures of the skull) is functionally classified as a(n):",o:["Amphiarthrosis","Diarthrosis","Synovial joint","Synarthrosis","Cartilaginous joint"],a:3},
{s:3,q:"Functionally, a joint that allows only slight movement (like the pubic symphysis or the intervertebral discs) is classified as a(n):",o:["Synarthrosis","Diarthrosis","Amphiarthrosis","Fibrous joint","Synovial joint"],a:2},
{s:3,q:"Functionally, a joint that is freely movable (like the knee, shoulder, or elbow) is classified as a(n):",o:["Synarthrosis","Amphiarthrosis","Diarthrosis","Suture","Syndesmosis"],a:2},
{s:3,q:"From the OpenStax review: Which of these joints is classified structurally as a fibrous joint?",o:["A synovial joint","The pubic symphysis","The intervertebral discs","The sutures of the skull","The knee joint"],a:3},
{s:3,q:"Joints can also be classified structurally by what physically holds them together. A joint where the articulating bones are united directly by hyaline cartilage or fibrocartilage is a:",o:["Fibrous joint","Cartilaginous joint","Synovial joint","Diarthrosis","Syndesmosis"],a:1},
{s:3,q:"From the OpenStax review: Synovial joints ________.",o:["Are held together by a solid mass of dense regular connective tissue.","Are classified functionally as synarthroses.","Are joints where the bones articulate with each other within a fluid-filled joint cavity.","Are formed strictly by endochondral ossification.","Never contain articular cartilage."],a:2},
{s:3,q:"Within a synovial joint, what specific structure creates the physical boundaries of the joint cavity and is composed of an outer fibrous capsule and an inner synovial membrane?",o:["The articular cartilage","The meniscus","The articular capsule","The bursa","The ligament"],a:2},
{s:3,q:"In a synovial joint, what is the primary function of the synovial fluid?",o:["To generate red blood cells","To act as a solid, immovable glue between bones","To lubricate the joint, reduce friction, and nourish the articular cartilage","To store yellow bone marrow","To synthesize Vitamin D"],a:2},
{s:3,q:"From the OpenStax review: Which type of fibrous joint connects the tibia and fibula using a long band of connective tissue/ligament?",o:["Syndesmosis","Suture","Symphysis","Synchondrosis","Gomphosis"],a:0},
{s:3,q:"The movement allowed by a joint that increases the angle between two articulating bones (such as straightening your arm at the elbow) is called:",o:["Flexion","Extension","Abduction","Adduction","Rotation"],a:1},
{s:3,q:"The movement allowed by a joint that decreases the angle between two articulating bones (such as bending your knee or elbow) is called:",o:["Flexion","Extension","Supination","Pronation","Circumduction"],a:0},
{s:3,q:"In anatomical movement, moving a limb laterally away from the midline of the body in the coronal plane is called:",o:["Adduction","Flexion","Abduction","Extension","Rotation"],a:2},
{s:3,q:"Bringing a limb back toward the midline of the body is called:",o:["Abduction","Adduction","Circumduction","Supination","Pronation"],a:1},
{s:3,q:"Which specific movement involves turning the palm of the hand to face upward or forward (anatomical position)?",o:["Pronation","Supination","Inversion","Eversion","Dorsiflexion"],a:1},
{s:3,q:"Which specific movement involves turning the palm of the hand to face downward or backward?",o:["Supination","Dorsiflexion","Pronation","Plantar flexion","Abduction"],a:2},
{s:3,q:"A specialized movement of the foot that bends the top of the foot upward toward the shin is called:",o:["Plantar flexion","Dorsiflexion","Inversion","Eversion","Circumduction"],a:1},
{s:3,q:"Pointing your toes downward (like standing on your tiptoes) is a specific movement called:",o:["Dorsiflexion","Supination","Plantar flexion","Eversion","Pronation"],a:2},
{s:3,q:"From the OpenStax review: Which of these joints is classified functionally as a biaxial diarthrosis (allowing movement in two planes)?",o:["The shoulder joint","The hip joint","The metacarpophalangeal joint (knuckle)","The elbow joint","The pubic symphysis"],a:2},
{s:3,q:"A ball-and-socket joint (like the shoulder or hip) is functionally classified as a multiaxial joint because it allows movement in multiple planes, including flexion/extension, abduction/adduction, and:",o:["Gliding","Rotation","Supination only","Pronation only","Inversion"],a:1},
{s:3,q:"Which type of synovial joint allows only for simple back-and-forth gliding movements between flat bone surfaces (e.g., between the carpal bones of the wrist)?",o:["Hinge joint","Pivot joint","Plane (gliding) joint","Saddle joint","Ball-and-socket joint"],a:2},
{s:3,q:"The elbow and the knee are classic examples of which type of synovial joint, which allows movement primarily in only one axis (uniaxial flexion and extension)?",o:["Hinge joint","Pivot joint","Condyloid joint","Saddle joint","Ball-and-socket joint"],a:0},
{s:3,q:"A Week 9 PollEv variant asks about bone landmarks related to joints. The round, smooth articulating surface at the very end of a bone that fits into another bone to form a joint is broadly called a:",o:["Fissure","Foramen","Condyle","Tuberosity","Trochanter"],a:2},
{s:3,q:"From the OpenStax review: Which of the following anatomical motions involves increasing or decreasing the angle of the foot at the ankle?",o:["Supination and Pronation","Dorsiflexion and Plantar flexion","Inversion and Eversion","Protraction and Retraction","Elevation and Depression"],a:1},
{s:3,q:"A meniscus is a specific structural feature found in some heavily stressed synovial joints (like the knee). What is a meniscus composed of?",o:["Hyaline cartilage","Fibrocartilage","Dense regular connective tissue","Elastic cartilage","Liquid synovial fluid"],a:1},
{s:3,q:"Bursae are small, fluid-filled sacs often found near synovial joints. What is their primary function?",o:["To produce red blood cells","To physically hold two bones together","To reduce friction where skin, ligaments, muscles, or tendons rub against bone","To synthesize Vitamin D","To store excess calcium for the joint"],a:2},
{s:3,q:"From the OpenStax review: What is a possible clinical consequence of a fracture to the femoral neck within the capsule of the hip joint?",o:["The femur immediately fuses to the pelvis.","The blood supply to the femoral head can be torn, resulting in bone tissue death (necrosis).","The synovial fluid turns into red bone marrow.","The body completely stops making parathyroid hormone.","The patient immediately develops rheumatoid arthritis in all body joints."],a:1},
{s:3,q:"Based on your lecture objectives regarding the interactions of the skeletal system: While the skeletal system stores calcium, the ________ system absorbs it from the diet, and the ________ system prevents it from being lost in the urine.",o:["Digestive; Urinary (Kidneys)","Respiratory; Integumentary","Nervous; Endocrine","Integumentary; Muscular","Cardiovascular; Lymphatic"],a:0}
];

/* ---------------------------------------------------------------------
   SLIDE IDENTIFICATION ROUND
   Real virtual-microscope slides from histologyguide.com (Univ. of Michigan).
   `thumb` = tissue overview image; `viewer` = full zoomable slide (opens in
   new tab / embedded viewer so students can examine cellular detail).
   --------------------------------------------------------------------- */
const HG = "https://histologyguide.com/slideview/";
const slideImg = d => `${HG}${d}/imgs/slide.png`;
const slideView = (d, n=1) => `${HG}${d}/05-slide-${n}.html`;

const SLIDES = [
// --- Tissue / structure identification ---
{dir:"MH-043-cancellous-and-compact-bone",cat:"Tissue ID",
 q:"This decalcified section shows two forms of bone: a dense solid outer region and an inner lattice of bony spikes (trabeculae) with marrow-filled spaces. What two tissues are shown?",
 o:["Hyaline cartilage and perichondrium","Compact bone (outer) and spongy/cancellous bone (inner)","Dense regular connective tissue and tendon","Elastic cartilage and bone marrow","Periosteum and articular cartilage"],a:1},

{dir:"MH-044-ground-bone",cat:"Tissue ID",
 q:"This is a ground (non-decalcified) cross-section of dried bone. It is built from circular units of concentric rings surrounding a central channel. Identify the tissue:",
 o:["Spongy bone trabeculae","Hyaline cartilage","Compact bone composed of osteons (Haversian systems)","Epiphyseal growth plate","Fibrocartilage"],a:2},

{dir:"MHS-203-bone",cat:"Tissue ID",
 q:"This developing long bone shows a hyaline cartilage model being progressively replaced by bone, with ordered columns of cartilage cells. What process is illustrated?",
 o:["Intramembranous ossification","Endochondral ossification","Appositional growth of compact bone","Fracture remodeling","Hematopoiesis"],a:1},

{dir:"MH-046-bone-development",cat:"Tissue ID",viewerN:1,
 q:"In this growing bone, a plate of hyaline cartilage sits between the epiphysis and the diaphysis and drives lengthening of the bone. This structure is the:",
 o:["Periosteum","Epiphyseal (growth) plate","Medullary cavity","Articular capsule","Osteon"],a:1},

{dir:"MHS-287-bone-development",cat:"Tissue ID",
 q:"These orderly columns of cartilage cells transitioning into newly formed bone (reserve → proliferating → hypertrophic → calcifying) are characteristic of which structure?",
 o:["The osteon of compact bone","The epiphyseal plate during endochondral ossification","The trabeculae of mature spongy bone","A healing fracture hematoma","The articular cartilage surface"],a:1},

{dir:"MH-136-trachea",cat:"Tissue ID",
 q:"The supportive C-shaped structure in this trachea wall has chondrocytes sitting in lacunae within a smooth, glassy matrix and is covered by a perichondrium. What cartilage is this?",
 o:["Elastic cartilage","Hyaline cartilage","Fibrocartilage","Compact bone","Dense irregular connective tissue"],a:1},

{dir:"MH-038-039-epiglottis",cat:"Tissue ID",thumbDir:"MH-038-epiglottis",
 q:"This core of the epiglottis is supported by a cartilage packed with branching elastic fibers, letting it bend and spring back. Identify the tissue:",
 o:["Hyaline cartilage","Fibrocartilage","Elastic cartilage","Spongy bone","Compact bone"],a:2},

{dir:"VH-040-ear",cat:"Tissue ID",
 q:"The flexible cartilage forming the framework of the external ear (pinna), rich in elastic fibers, is:",
 o:["Hyaline cartilage","Elastic cartilage","Fibrocartilage","Bone","Adipose tissue"],a:1},

{dir:"MH-040-intervertebral-disk",cat:"Tissue ID",
 q:"The intervertebral disc contains a cartilage with thick, visible bundles of collagen between rows of chondrocytes, resisting both compression and tension. This tissue is:",
 o:["Hyaline cartilage","Elastic cartilage","Fibrocartilage","Compact bone","Adipose tissue"],a:2},

// --- Cellular makeup of bone (zoom into the linked slide to examine cells) ---
{dir:"MH-045-bone",cat:"Bone cells",
 q:"Zoom into this decalcified bone. Embedded throughout the calcified matrix, each sitting alone inside a small space (lacuna), are the mature, non-dividing bone cells. These are:",
 o:["Chondrocytes","Osteoblasts","Osteocytes","Osteoclasts","Fibroblasts"],a:2},

{dir:"MHS-203-bone",cat:"Bone cells",
 q:"Examine the surfaces of the newly forming bone trabeculae here. The plump cuboidal cells lined up in a row, actively secreting osteoid (new bone matrix), are:",
 o:["Osteocytes trapped in lacunae","Osteoblasts","Osteoclasts","Chondrocytes","Red blood cells"],a:1},

{dir:"MHS-287-bone-development",cat:"Bone cells",
 q:"Along the spicules of developing bone you can find very large, multinucleated cells sitting in scalloped resorption pits (Howship's lacunae), breaking down bone. These are:",
 o:["Osteoblasts","Osteocytes","Osteoclasts","Osteoprogenitor cells","Chondroblasts"],a:2},

{dir:"MH-044-ground-bone",cat:"Bone cells",
 q:"Zoom into one osteon in this ground bone. The single large opening in the very center — which in life carries blood vessels and nerves — is the:",
 o:["Lacuna","Canaliculus","Central (Haversian) canal","Trabecula","Resorption pit"],a:2},

{dir:"MHS-233-ground-bone",cat:"Bone cells",
 q:"In this India-ink ground bone preparation, the small dark almond-shaped spaces (which housed living osteocytes) arranged in rings are called:",
 o:["Central (Haversian) canals","Canaliculi","Lacunae","Trabeculae","Lamellae"],a:2},

{dir:"MHS-202-ground-bone",cat:"Bone cells",
 q:"Zoom in on the dark spaces in this ground bone: fine hair-like channels radiate outward and interconnect the spaces, allowing osteocytes to exchange nutrients. These channels are:",
 o:["Canaliculi","Central canals","Perforating (Volkmann's) canals","Medullary cavities","Concentric lamellae"],a:0},

{dir:"MH-044-ground-bone",cat:"Bone cells",viewerN:1,altKey:"lamellae",
 q:"Look at the concentric rings of bone matrix laid down around the central canal of each osteon. These individual rings of calcified matrix are called:",
 o:["Canaliculi","Concentric lamellae","Trabeculae","Lacunae","Perforating canals"],a:1}
];

// expose for app.js
window.QUIZ = { SECTIONS, QUESTIONS, SLIDES, slideImg, slideView };
